name: Build and Publish ArangoPG Image

on:
  push:
    branches: [develop, main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup just
        uses: extractions/setup-just@v1
        with:
          just-version: '1.28.0'

      - name: Build and publish ArangoPG image
        run: |
          branch_name=$(echo ${GITHUB_REF#refs/heads/})
          just build-publish-arangopg-image \
            $branch_name-${{ github.sha }} \
            ${{ secrets.DOCKERHUB_USER }} \
            ${{ secrets.DOCKER_PASS }} \
            dictybase restic-redis-arangopg
